from usim800_slideshow.usim800.Request_slideshow.Request_httpconnection import request_httpconnection
from usim800_slideshow.usim800.Request_slideshow.Request_ftpconnection import request_ftpconnection
